language: php

php:
  - '7.1'
  - '7.2'
  - 'nightly'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls
  - composer install --dev --no-interaction
  - yes | pecl install imagick

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
